""" Benchmarking the OptiFit algorithm using subsets of datasets """
import Bio.SeqIO
import numpy.random
import shutil

subworkflow prep_samples:
    workdir:
        "../1_prep_samples/"


datasets = ["soil"]
refs = ["silva"]
regions = ['bact_v4']
methods = ["open", "closed"]
printrefs = ['f']
seeds = range(1,2)

random_weight_options = {'simple', 'abundance', 'distance'}

rule split_weighted_subsample:
    input:
        code="../../code/py/split_weighted_subsample.py"
        fasta=prep_samples("data/{dataset}/silva/processed/{dataset}.fasta"),
        count=prep_samples("data/{dataset}/{ref}/processed/{dataset}.count_table"),
        dist=prep_samples("results/{dataset}/{ref}/{dataset}.dist")
    output:
        fasta="data/{dataset}/weight_{weight}/reffrac_{ref_frac}/samplefrac_{sample_frac}/seed_{seed}/{dataset}.fasta",
        count="data/{dataset}/weight_{weight}/reffrac_{ref_frac}/samplefrac_{sample_frac}/seed_{seed}/{dataset}.count_table",
        dist="data/{dataset}/weight_{weight}/reffrac_{ref_frac}/samplefrac_{sample_frac}/seed_{seed}/{dataset}.dist",
        ref_accnos="data/{dataset}/weight_{weight}/reffrac_{ref_frac}/samplefrac_{sample_frac}/seed_{seed}/ref.fasta"
    script:
        "../../code/py/split_weighted_subsample.py"





