---
title: "Did MCC results change?"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      fig.path = "figures/"
                      )
```

```{r deps}
library(glue)
library(here)
library(tidyverse)
theme_set(theme_bw())
```

Why does it look like OptiClust performed ~4% worse than OptiFit with the split strategy?

## Did OptiClust results change?

[March 2021 commit: `0b80681`](https://github.com/SchlossLab/Sovacool_OptiFit_2021/commits/main/subworkflows/1_prep_samples/results/opticlust_results.tsv)


```{r opticlust}
opticlust <- c('Nov-2020_5d87338', 'Mar-2021_0b80681') %>% 
  map_dfr(function(file) {
    read_tsv(here('exploratory', '2021', 'did-results-change', 
                glue('opticlust_results_{file}.tsv'))) %>% 
    mutate(file = file)
  })

opticlust %>% group_by(file) %>% summarize(min_mcc = min(mcc),
                                           median_mcc = median(mcc),
                                           max_mcc = max(mcc))

opticlust %>% filter(dataset == 'human' | dataset == 'mouse') %>% 
  group_by(file, dataset) %>% 
  summarize(min_mcc = min(mcc),
            median_mcc = median(mcc),
            max_mcc = max(mcc))
```

Nope!

## Did OptiFit results change?

```{r optifit}
optifit <- c('Dec-2020_5fcc830',
             'Apr-2021_c6fcdbd', 
             'Jul-2021_4090079') %>% 
  map_dfr(function(file) {
    read_tsv(here('exploratory', '2021', 'did-results-change', 
                glue('optifit_split_results_{file}.tsv'))) %>% 
    mutate(file = file)
  })

optifit %>% filter(dataset == 'human' | dataset == 'mouse') %>% 
  group_by(file, dataset) %>% 
  summarize(min_mcc = min(mcc),
            median_mcc = median(mcc),
            max_mcc = max(mcc))

optifit %>% 
  filter(dataset == 'human' | dataset == 'mouse') %>% 
  ggplot(aes(x = file, y = mcc, color = dataset)) +
  geom_boxplot()
```


Yeah! OptiFit results improved. What changed? I don't think I've updated mothur since December.
